<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Why should you use the moderndive package for intro linear regression? • moderndive</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha256-916EbMg70RQy9LHiGkXzG8hSg9EdNy97GazNG/aiY1w=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha256-U5ZEeKfGNOja007MMD3YBI0A3OSZOQbeG6z2f2Y0hu8=" crossorigin="anonymous"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.1/css/all.min.css" integrity="sha256-nAmazAk6vS34Xqo0BSrTb+abbtFlgsFK7NKSi6o7Y78=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.1/css/v4-shims.min.css" integrity="sha256-6qHlizsOWFskGlwVOKuns+D1nB6ssZrHQrNj1wGplHc=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.4/clipboard.min.js" integrity="sha256-FiZwavyI2V6+EXO1U+xzLG3IKldpiTFf3153ea9zikQ=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.9.4/headroom.min.js" integrity="sha256-DJFC1kqIhelURkuza0AvYal5RxMtpzLjFhsnVIeuk+U=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.9.4/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Why should you use the moderndive package for intro linear regression?">
<meta property="og:description" content="">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">moderndive</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.2.0.9000</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/why-moderndive.html">Why should you use the moderndive package for intro linear regression?</a>
    </li>
  </ul>
</li>
<li>
  <a href="../news/index.html">Changelog</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/ModernDive/moderndive_package">
    <span class="fab fa fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>Why should you use the moderndive package for intro linear regression?</h1>
                        <h4 class="author">Albert Y. Kim &amp; Chester Ismay</h4>
            
            <h4 class="date">2019-06-22</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/ModernDive/moderndive_package/blob/master/vignettes/why-moderndive.Rmd"><code>vignettes/why-moderndive.Rmd</code></a></small>
      <div class="hidden name"><code>why-moderndive.Rmd</code></div>

    </div>

    
    
<div id="intro" class="section level2">
<h2 class="hasAnchor">
<a href="#intro" class="anchor"></a>Intro</h2>
<p>Linear regression has long been a staple of introductory statistics courses. While the timing of when to introduce it may have changed (many argue that descriptive regression should be done ASAP and then revisited later after statistical inference has been covered), it’s overall importance in the intro stats curriculum remains the same.</p>
<p>Let’s consider data gathered from end of semester student evaluations for 463 professors from the University of Texas at Austin (see <a href="https://www.openintro.org/stat/data/?data=evals" target="_blank">openintro.org</a> for more details). Here is a random sample of 5 instructors and a subset of 8 of the 13 variables included, where the outcome variable of interest is the teaching evaluation <code>score</code> out of 5 as given by students:</p>
<table class="table">
<thead><tr class="header">
<th align="right">ID</th>
<th align="right">score</th>
<th align="right">age</th>
<th align="right">bty_avg</th>
<th align="left">gender</th>
<th align="left">ethnicity</th>
<th align="left">language</th>
<th align="left">rank</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="right">290</td>
<td align="right">3.6</td>
<td align="right">34</td>
<td align="right">6.667</td>
<td align="left">male</td>
<td align="left">not minority</td>
<td align="left">english</td>
<td align="left">tenure track</td>
</tr>
<tr class="even">
<td align="right">341</td>
<td align="right">4.9</td>
<td align="right">43</td>
<td align="right">3.500</td>
<td align="left">male</td>
<td align="left">not minority</td>
<td align="left">english</td>
<td align="left">tenure track</td>
</tr>
<tr class="odd">
<td align="right">199</td>
<td align="right">3.3</td>
<td align="right">47</td>
<td align="right">2.333</td>
<td align="left">male</td>
<td align="left">minority</td>
<td align="left">english</td>
<td align="left">tenured</td>
</tr>
<tr class="even">
<td align="right">47</td>
<td align="right">4.4</td>
<td align="right">33</td>
<td align="right">4.667</td>
<td align="left">female</td>
<td align="left">not minority</td>
<td align="left">english</td>
<td align="left">tenure track</td>
</tr>
<tr class="odd">
<td align="right">215</td>
<td align="right">4.7</td>
<td align="right">60</td>
<td align="right">3.667</td>
<td align="left">male</td>
<td align="left">not minority</td>
<td align="left">english</td>
<td align="left">tenured</td>
</tr>
</tbody>
</table>
<p>The data is included in <code>evals</code> dataset in the <a href="https://moderndive.github.io/moderndive/" target="_blank"><code>moderndive</code></a> R package for tidyverse-friendly introductory linear regression. Let’s fit a regression model of teaching <code>score</code> as a function of instructor <code>age</code>:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" data-line-number="1"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span>(moderndive)</a>
<a class="sourceLine" id="cb1-2" data-line-number="2">score_model &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span>(score <span class="op">~</span><span class="st"> </span>age, <span class="dt">data =</span> evals)</a></code></pre></div>
<div id="regression-analysis-the-good-old-fashioned-way" class="section level3">
<h3 class="hasAnchor">
<a href="#regression-analysis-the-good-old-fashioned-way" class="anchor"></a>Regression analysis the “good old-fashioned” way</h3>
<p>Let’s analyze the output of the fitted model <code>score_model</code> “the good old fashioned way”: using <code><a href="https://rdrr.io/r/stats/summary.lm.html">summary.lm()</a></code>.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb2-1" data-line-number="1"><span class="kw"><a href="https://rdrr.io/r/base/summary.html">summary</a></span>(score_model)</a>
<a class="sourceLine" id="cb2-2" data-line-number="2"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb2-3" data-line-number="3"><span class="co">#&gt; Call:</span></a>
<a class="sourceLine" id="cb2-4" data-line-number="4"><span class="co">#&gt; lm(formula = score ~ age, data = evals)</span></a>
<a class="sourceLine" id="cb2-5" data-line-number="5"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb2-6" data-line-number="6"><span class="co">#&gt; Residuals:</span></a>
<a class="sourceLine" id="cb2-7" data-line-number="7"><span class="co">#&gt;     Min      1Q  Median      3Q     Max </span></a>
<a class="sourceLine" id="cb2-8" data-line-number="8"><span class="co">#&gt; -1.9185 -0.3531  0.1172  0.4172  0.8825 </span></a>
<a class="sourceLine" id="cb2-9" data-line-number="9"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb2-10" data-line-number="10"><span class="co">#&gt; Coefficients:</span></a>
<a class="sourceLine" id="cb2-11" data-line-number="11"><span class="co">#&gt;              Estimate Std. Error t value Pr(&gt;|t|)    </span></a>
<a class="sourceLine" id="cb2-12" data-line-number="12"><span class="co">#&gt; (Intercept)  4.461932   0.126778  35.195   &lt;2e-16 ***</span></a>
<a class="sourceLine" id="cb2-13" data-line-number="13"><span class="co">#&gt; age         -0.005938   0.002569  -2.311   0.0213 *  </span></a>
<a class="sourceLine" id="cb2-14" data-line-number="14"><span class="co">#&gt; ---</span></a>
<a class="sourceLine" id="cb2-15" data-line-number="15"><span class="co">#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></a>
<a class="sourceLine" id="cb2-16" data-line-number="16"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb2-17" data-line-number="17"><span class="co">#&gt; Residual standard error: 0.5413 on 461 degrees of freedom</span></a>
<a class="sourceLine" id="cb2-18" data-line-number="18"><span class="co">#&gt; Multiple R-squared:  0.01146,    Adjusted R-squared:  0.009311 </span></a>
<a class="sourceLine" id="cb2-19" data-line-number="19"><span class="co">#&gt; F-statistic: 5.342 on 1 and 461 DF,  p-value: 0.02125</span></a></code></pre></div>
<p>Here are five common student comments/questions we’ve heard over the years in our intro stats courses based on this output:</p>
<ol style="list-style-type: decimal">
<li>“Wow! Look at those p-value stars! Stars are good, so I must get more stars somehow.”</li>
<li>“How do extract the values in the regression table?”</li>
<li>“Where are the fitted/predicted values and residuals?”</li>
<li>“How do I apply this model to a new set of data to make predictions?”</li>
<li>“What is all this other stuff at the bottom?”</li>
</ol>
</div>
<div id="regression-analysis-the-tidyverse-friendly-way" class="section level3">
<h3 class="hasAnchor">
<a href="#regression-analysis-the-tidyverse-friendly-way" class="anchor"></a>Regression analysis the tidyverse-friendly way</h3>
<p>To address these comments/questions, we’ve included three functions in the <code>moderndive</code> package that takes as a fitted model as input (in this case <code>score_model</code>) and returns the same information as <code><a href="https://rdrr.io/r/base/summary.html">summary(score_model)</a></code> but in a tidyverse-friendly way:</p>
<ol style="list-style-type: decimal">
<li>
<p>Get a tidy regression table <strong>with</strong> confidence intervals:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" data-line-number="1"><span class="kw"><a href="../reference/get_regression_table.html">get_regression_table</a></span>(score_model)</a>
<a class="sourceLine" id="cb3-2" data-line-number="2"><span class="co">#&gt; # A tibble: 2 x 7</span></a>
<a class="sourceLine" id="cb3-3" data-line-number="3"><span class="co">#&gt;   term      estimate std_error statistic p_value lower_ci upper_ci</span></a>
<a class="sourceLine" id="cb3-4" data-line-number="4"><span class="co">#&gt;   &lt;chr&gt;        &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;</span></a>
<a class="sourceLine" id="cb3-5" data-line-number="5"><span class="co">#&gt; 1 intercept    4.46      0.127     35.2    0        4.21     4.71 </span></a>
<a class="sourceLine" id="cb3-6" data-line-number="6"><span class="co">#&gt; 2 age         -0.006     0.003     -2.31   0.021   -0.011   -0.001</span></a></code></pre></div>
</li>
<li>
<p>Get information on each point/observation in your regression, including fitted/predicted values &amp; residuals, in a single data frame:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" data-line-number="1"><span class="kw"><a href="../reference/get_regression_points.html">get_regression_points</a></span>(score_model)</a>
<a class="sourceLine" id="cb4-2" data-line-number="2"><span class="co">#&gt; # A tibble: 463 x 5</span></a>
<a class="sourceLine" id="cb4-3" data-line-number="3"><span class="co">#&gt;       ID score   age score_hat residual</span></a>
<a class="sourceLine" id="cb4-4" data-line-number="4"><span class="co">#&gt;    &lt;int&gt; &lt;dbl&gt; &lt;int&gt;     &lt;dbl&gt;    &lt;dbl&gt;</span></a>
<a class="sourceLine" id="cb4-5" data-line-number="5"><span class="co">#&gt;  1     1   4.7    36      4.25    0.452</span></a>
<a class="sourceLine" id="cb4-6" data-line-number="6"><span class="co">#&gt;  2     2   4.1    36      4.25   -0.148</span></a>
<a class="sourceLine" id="cb4-7" data-line-number="7"><span class="co">#&gt;  3     3   3.9    36      4.25   -0.348</span></a>
<a class="sourceLine" id="cb4-8" data-line-number="8"><span class="co">#&gt;  4     4   4.8    36      4.25    0.552</span></a>
<a class="sourceLine" id="cb4-9" data-line-number="9"><span class="co">#&gt;  5     5   4.6    59      4.11    0.488</span></a>
<a class="sourceLine" id="cb4-10" data-line-number="10"><span class="co">#&gt;  6     6   4.3    59      4.11    0.188</span></a>
<a class="sourceLine" id="cb4-11" data-line-number="11"><span class="co">#&gt;  7     7   2.8    59      4.11   -1.31 </span></a>
<a class="sourceLine" id="cb4-12" data-line-number="12"><span class="co">#&gt;  8     8   4.1    51      4.16   -0.059</span></a>
<a class="sourceLine" id="cb4-13" data-line-number="13"><span class="co">#&gt;  9     9   3.4    51      4.16   -0.759</span></a>
<a class="sourceLine" id="cb4-14" data-line-number="14"><span class="co">#&gt; 10    10   4.5    40      4.22    0.276</span></a>
<a class="sourceLine" id="cb4-15" data-line-number="15"><span class="co">#&gt; # … with 453 more rows</span></a></code></pre></div>
</li>
<li>
<p>Get scalar summaries of a regression fit including <span class="math inline">\(R^2\)</span> and <span class="math inline">\(R^2_{adj}\)</span> but also the (root) mean-squared error:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" data-line-number="1"><span class="kw"><a href="../reference/get_regression_summaries.html">get_regression_summaries</a></span>(score_model)</a>
<a class="sourceLine" id="cb5-2" data-line-number="2"><span class="co">#&gt; # A tibble: 1 x 8</span></a>
<a class="sourceLine" id="cb5-3" data-line-number="3"><span class="co">#&gt;   r_squared adj_r_squared   mse  rmse sigma statistic p_value    df</span></a>
<a class="sourceLine" id="cb5-4" data-line-number="4"><span class="co">#&gt;       &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;</span></a>
<a class="sourceLine" id="cb5-5" data-line-number="5"><span class="co">#&gt; 1     0.011         0.009 0.292 0.540 0.541      5.34   0.021     2</span></a></code></pre></div>
</li>
</ol>
</div>
<div id="why-should-you-use-the-moderndive-package" class="section level3">
<h3 class="hasAnchor">
<a href="#why-should-you-use-the-moderndive-package" class="anchor"></a>Why should you use the <code>moderndive</code> package?</h3>
<p>We think that these three functions included in the <code>moderndive</code> package are effective pedagogical tools that can help address the above five common student comments/questions. Why now argue why.</p>
<hr>
</div>
</div>
<div id="less-p-value-stars-more-confidence-intervals" class="section level2">
<h2 class="hasAnchor">
<a href="#less-p-value-stars-more-confidence-intervals" class="anchor"></a>1. Less p-value stars, more confidence intervals</h2>
<p>The first common student comment/question:</p>
<blockquote>
<p>“Wow! Look at those p-value stars! Stars are good, so I must get more stars somehow.”</p>
</blockquote>
<p>We argue that the <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> output is deficient in an intro stats setting because:</p>
<ul>
<li>The <code>Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code> only encourage <strong>p-hacking</strong>. In case you have not yet been convinced of the perniciousness of p-hacking, perhaps comedian <a href="https://www.youtube.com/watch?v=0Rnq1NpHdmw" target="_blank">John Oliver can convince you</a>.<br>
</li>
<li>While not a silver bullet for eliminating misinterpretations of statistical inference results, confidence intervals at least give students a sense of the practical significance and not just the statistical significance of the results. These should be included in the regression table output.</li>
</ul>
<p>Instead of <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code>, let’s use the <code><a href="../reference/get_regression_table.html">get_regression_table()</a></code> function in the <code>moderndive</code> package:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb6-1" data-line-number="1"><span class="kw"><a href="../reference/get_regression_table.html">get_regression_table</a></span>(score_model)</a>
<a class="sourceLine" id="cb6-2" data-line-number="2"><span class="co">#&gt; # A tibble: 2 x 7</span></a>
<a class="sourceLine" id="cb6-3" data-line-number="3"><span class="co">#&gt;   term      estimate std_error statistic p_value lower_ci upper_ci</span></a>
<a class="sourceLine" id="cb6-4" data-line-number="4"><span class="co">#&gt;   &lt;chr&gt;        &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;</span></a>
<a class="sourceLine" id="cb6-5" data-line-number="5"><span class="co">#&gt; 1 intercept    4.46      0.127     35.2    0        4.21     4.71 </span></a>
<a class="sourceLine" id="cb6-6" data-line-number="6"><span class="co">#&gt; 2 age         -0.006     0.003     -2.31   0.021   -0.011   -0.001</span></a></code></pre></div>
<p>Confidence intervals! By including them in the output, we can easily emphasize to students that they “surround” the point estimates in the <code>estimate</code> column. Note the confidence level is defaulted to 95%.</p>
<hr>
</div>
<div id="outputs-as-tidy-tibbles" class="section level2">
<h2 class="hasAnchor">
<a href="#outputs-as-tidy-tibbles" class="anchor"></a>2. Outputs as tidy tibbles!</h2>
<p>All the functions in the <code>moderndive</code> package return tidy tibbles! So for example, by piping the above <code><a href="../reference/get_regression_table.html">get_regression_table(score_model)</a></code> output into the <code>kable()</code> function from the <code>knitr</code> package, you can have aesthetically pleasing regression tables in R Markdown documents, instead of jarring computer output font:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" data-line-number="1"><span class="kw"><a href="../reference/get_regression_table.html">get_regression_table</a></span>(score_model) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb7-2" data-line-number="2"><span class="st">  </span>knitr<span class="op">::</span><span class="kw"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span>()</a></code></pre></div>
<table class="table">
<thead><tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std_error</th>
<th align="right">statistic</th>
<th align="right">p_value</th>
<th align="right">lower_ci</th>
<th align="right">upper_ci</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">intercept</td>
<td align="right">4.462</td>
<td align="right">0.127</td>
<td align="right">35.195</td>
<td align="right">0.000</td>
<td align="right">4.213</td>
<td align="right">4.711</td>
</tr>
<tr class="even">
<td align="left">age</td>
<td align="right">-0.006</td>
<td align="right">0.003</td>
<td align="right">-2.311</td>
<td align="right">0.021</td>
<td align="right">-0.011</td>
<td align="right">-0.001</td>
</tr>
</tbody>
</table>
<p>Now let’s address the second common student comment/question:</p>
<blockquote>
<p>“How do extract the values in the regression table?”</p>
</blockquote>
<p>While one might argue that extracting the intercept and slope coefficients can be simply done using <code><a href="https://rdrr.io/r/stats/coef.html">coefficients(score_model)</a></code>, what about the standard errors? A Google query of “<em>how do I extract standard errors from lm in r</em>” yields results from <a href="https://stat.ethz.ch/pipermail/r-help/2008-April/160538.html" target="_blank">the R mailing list</a> and from <a href="https://stats.stackexchange.com/questions/27511/extract-standard-errors-of-coefficient-linear-regression-r" target="_blank">crossvalidated</a> suggesting we run:</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" data-line-number="1"><span class="kw"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span>(<span class="kw"><a href="https://rdrr.io/r/base/diag.html">diag</a></span>(<span class="kw"><a href="https://rdrr.io/r/stats/vcov.html">vcov</a></span>(score_model)))</a>
<a class="sourceLine" id="cb8-2" data-line-number="2"><span class="co">#&gt; (Intercept)         age </span></a>
<a class="sourceLine" id="cb8-3" data-line-number="3"><span class="co">#&gt; 0.126778499 0.002569157</span></a></code></pre></div>
<p>Say what?!? It shouldn’t be this hard! However since <code><a href="../reference/get_regression_table.html">get_regression_table()</a></code> returns a data frame/tidy tibble, you can easily extract columns using <code><a href="https://dplyr.tidyverse.org/reference/pull.html">dplyr::pull()</a></code>:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" data-line-number="1"><span class="kw"><a href="../reference/get_regression_table.html">get_regression_table</a></span>(score_model) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb9-2" data-line-number="2"><span class="st">  </span><span class="kw">pull</span>(std_error)</a>
<a class="sourceLine" id="cb9-3" data-line-number="3"><span class="co">#&gt; [1] 0.127 0.003</span></a></code></pre></div>
<p>or equivalently you can use the <code>$</code> sign operator from base R:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb10-1" data-line-number="1"><span class="kw"><a href="../reference/get_regression_table.html">get_regression_table</a></span>(score_model)<span class="op">$</span>std_error</a>
<a class="sourceLine" id="cb10-2" data-line-number="2"><span class="co">#&gt; [1] 0.127 0.003</span></a></code></pre></div>
<hr>
</div>
<div id="birds-of-a-feather-should-flock-together-fitted-values-residuals" class="section level2">
<h2 class="hasAnchor">
<a href="#birds-of-a-feather-should-flock-together-fitted-values-residuals" class="anchor"></a>3. Birds of a feather should flock together: Fitted values &amp; residuals</h2>
<p>The third common student comment/question:</p>
<blockquote>
<p>“Where are the fitted/predicted values and residuals?”</p>
</blockquote>
<p>How can we extract point-by-point information from a regression model, such as the fitted/predicted values and the residuals? (Note we’ll only display the first 10 of such values, and not all n = 463, for brevity’s sake)</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" data-line-number="1"><span class="kw"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span>(score_model)</a></code></pre></div>
<pre><code>#&gt;        1        2        3        4        5        6        7        8 
#&gt; 4.248156 4.248156 4.248156 4.248156 4.111577 4.111577 4.111577 4.159083 
#&gt;        9       10 
#&gt; 4.159083 4.224403</code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" data-line-number="1"><span class="kw"><a href="https://rdrr.io/r/stats/residuals.html">residuals</a></span>(score_model)</a></code></pre></div>
<pre><code>#&gt;           1           2           3           4           5           6 
#&gt;  0.45184376 -0.14815624 -0.34815624  0.55184376  0.48842294  0.18842294 
#&gt;           7           8           9          10 
#&gt; -1.31157706 -0.05908286 -0.75908286  0.27559666</code></pre>
<p>But why have the original explantory/predictor <code>age</code> and outcome variable <code>score</code> in <code>evals</code>, the fitted/predicted values <code>score_hat</code>, and <code>residual</code> floating around in separate pieces? Since each observation relates to the same instructor, wouldn’t it make sense to organize them together? This is where <code><a href="../reference/get_regression_points.html">get_regression_points()</a></code> shines!</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" data-line-number="1"><span class="kw"><a href="../reference/get_regression_points.html">get_regression_points</a></span>(score_model)</a></code></pre></div>
<pre><code>#&gt; # A tibble: 10 x 5
#&gt;       ID score   age score_hat residual
#&gt;    &lt;int&gt; &lt;dbl&gt; &lt;int&gt;     &lt;dbl&gt;    &lt;dbl&gt;
#&gt;  1     1   4.7    36      4.25    0.452
#&gt;  2     2   4.1    36      4.25   -0.148
#&gt;  3     3   3.9    36      4.25   -0.348
#&gt;  4     4   4.8    36      4.25    0.552
#&gt;  5     5   4.6    59      4.11    0.488
#&gt;  6     6   4.3    59      4.11    0.188
#&gt;  7     7   2.8    59      4.11   -1.31 
#&gt;  8     8   4.1    51      4.16   -0.059
#&gt;  9     9   3.4    51      4.16   -0.759
#&gt; 10    10   4.5    40      4.22    0.276</code></pre>
<p>Observe that the original outcome variable <code>score</code> and explanatory/predictor variable <code>age</code> are now supplemented with the fitted/predicted value <code>score_hat</code> and <code>residual</code> columns. By putting the fitted/predicted values and the residuals next to the original data, we argue that the computation of these values is less opaque. For example in class, instructors can write out by hand how all the values in the first row, corresponding to the first instructor, are computed.</p>
<p>Furthermore, recall that all outputs in the <code>moderndive</code> package are data frames/tidy tibbles, thus you can easily create custom residual analysis plots, instead of the default ones yielded by <code><a href="https://rdrr.io/r/graphics/plot.html">plot(score_model)</a></code>. For example, we create:</p>
<ul>
<li>A histogram of all residuals to investigate normality.</li>
<li>A <em>partial residual plot</em> of the relationship of the residuals vs all explanatory/predictor variables to investigate the presence of heteroskedasticity; in this case a scatterplot of the residuals over <code>age</code>.</li>
</ul>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" data-line-number="1">score_model_points &lt;-<span class="st"> </span><span class="kw"><a href="../reference/get_regression_points.html">get_regression_points</a></span>(score_model)</a>
<a class="sourceLine" id="cb17-2" data-line-number="2"></a>
<a class="sourceLine" id="cb17-3" data-line-number="3"><span class="co"># Histogram of residuals:</span></a>
<a class="sourceLine" id="cb17-4" data-line-number="4"><span class="kw">ggplot</span>(score_model_points, <span class="kw">aes</span>(<span class="dt">x =</span> residual)) <span class="op">+</span></a>
<a class="sourceLine" id="cb17-5" data-line-number="5"><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">20</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb17-6" data-line-number="6"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">"Histogram of residuals"</span>)</a>
<a class="sourceLine" id="cb17-7" data-line-number="7"></a>
<a class="sourceLine" id="cb17-8" data-line-number="8"><span class="co"># Investigating patterns:</span></a>
<a class="sourceLine" id="cb17-9" data-line-number="9"><span class="kw">ggplot</span>(score_model_points, <span class="kw">aes</span>(<span class="dt">x =</span> age, <span class="dt">y =</span> residual)) <span class="op">+</span></a>
<a class="sourceLine" id="cb17-10" data-line-number="10"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb17-11" data-line-number="11"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">"Residuals over age"</span>)</a></code></pre></div>
<p><img src="why-moderndive_files/figure-html/unnamed-chunk-20-1.png" width="698.181818181818"><img src="why-moderndive_files/figure-html/unnamed-chunk-20-2.png" width="698.181818181818"></p>
<hr>
</div>
<div id="babys-first-kaggle-predictive-modeling-competition-submission" class="section level2">
<h2 class="hasAnchor">
<a href="#babys-first-kaggle-predictive-modeling-competition-submission" class="anchor"></a>4. Baby’s first Kaggle predictive modeling competition submission!</h2>
<p>The fourth common student comment/question:</p>
<blockquote>
<p>“How do I apply this model to a new set of data to make predictions?”</p>
</blockquote>
<p>With the fields of machine learning and artifical intelligence gaining prominence, the importance of predictive modeling cannot be understated. Therefore, we’ve designed the <code><a href="../reference/get_regression_points.html">get_regression_points()</a></code> function to allow for a <code>newdata</code> argument to quickly apply a previously fitted model to “new” observations.</p>
<p>Let’s create an artificial “new” dataset which is a subset of the original <code>evals</code> data with the outcome variable <code>score</code> removed and use it as the <code>newdata</code> argument:</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb18-1" data-line-number="1">new_evals &lt;-<span class="st"> </span>evals <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb18-2" data-line-number="2"><span class="st">  </span><span class="kw">sample_n</span>(<span class="dv">4</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb18-3" data-line-number="3"><span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>score)</a>
<a class="sourceLine" id="cb18-4" data-line-number="4">new_evals</a>
<a class="sourceLine" id="cb18-5" data-line-number="5"><span class="co">#&gt; # A tibble: 4 x 12</span></a>
<a class="sourceLine" id="cb18-6" data-line-number="6"><span class="co">#&gt;      ID   age bty_avg gender ethnicity language rank  pic_outfit pic_color</span></a>
<a class="sourceLine" id="cb18-7" data-line-number="7"><span class="co">#&gt;   &lt;int&gt; &lt;int&gt;   &lt;dbl&gt; &lt;fct&gt;  &lt;fct&gt;     &lt;fct&gt;    &lt;fct&gt; &lt;fct&gt;      &lt;fct&gt;    </span></a>
<a class="sourceLine" id="cb18-8" data-line-number="8"><span class="co">#&gt; 1   354    50    3.33 male   minority  english  teac… not formal color    </span></a>
<a class="sourceLine" id="cb18-9" data-line-number="9"><span class="co">#&gt; 2   140    34    7.83 female not mino… english  tenu… not formal color    </span></a>
<a class="sourceLine" id="cb18-10" data-line-number="10"><span class="co">#&gt; 3   334    50    7.17 male   not mino… english  tenu… not formal color    </span></a>
<a class="sourceLine" id="cb18-11" data-line-number="11"><span class="co">#&gt; 4   148    52    4.83 male   minority  non-eng… tenu… formal     color    </span></a>
<a class="sourceLine" id="cb18-12" data-line-number="12"><span class="co">#&gt; # … with 3 more variables: cls_did_eval &lt;int&gt;, cls_students &lt;int&gt;,</span></a>
<a class="sourceLine" id="cb18-13" data-line-number="13"><span class="co">#&gt; #   cls_level &lt;fct&gt;</span></a>
<a class="sourceLine" id="cb18-14" data-line-number="14"></a>
<a class="sourceLine" id="cb18-15" data-line-number="15"><span class="kw"><a href="../reference/get_regression_points.html">get_regression_points</a></span>(score_model, <span class="dt">newdata =</span> new_evals)</a>
<a class="sourceLine" id="cb18-16" data-line-number="16"><span class="co">#&gt; # A tibble: 4 x 3</span></a>
<a class="sourceLine" id="cb18-17" data-line-number="17"><span class="co">#&gt;      ID   age score_hat</span></a>
<a class="sourceLine" id="cb18-18" data-line-number="18"><span class="co">#&gt;   &lt;int&gt; &lt;int&gt;     &lt;dbl&gt;</span></a>
<a class="sourceLine" id="cb18-19" data-line-number="19"><span class="co">#&gt; 1     1    50      4.16</span></a>
<a class="sourceLine" id="cb18-20" data-line-number="20"><span class="co">#&gt; 2     2    34      4.26</span></a>
<a class="sourceLine" id="cb18-21" data-line-number="21"><span class="co">#&gt; 3     3    50      4.16</span></a>
<a class="sourceLine" id="cb18-22" data-line-number="22"><span class="co">#&gt; 4     4    52      4.15</span></a></code></pre></div>
<p><code>score_hat</code> are the predicted values! Let’s do another example, this time using the Kaggle <a href="https://www.kaggle.com/c/house-prices-advanced-regression-techniques" target="_blank">House Prices: Advanced Regression Techniques</a> practice competition.</p>
<p><img src="kaggle.png" width="500px" style="display: block; margin: auto;"></p>
<p>This Kaggle competition requires you to fit/train a model to the provided <code>train.csv</code> training set to make predictions of house prices in the provided <code>test.csv</code> test set. Here is code for a “baby’s first Kaggle competition” submission that will:</p>
<ol style="list-style-type: decimal">
<li>Read in the training and test data (that we posted on GitHub).</li>
<li>Fit a naive model of house sale price as a function of year sold.</li>
<li>Write a <code>submission.csv</code> file that can be submitted to Kaggle. Note the use of the <code>ID</code> argument to indicate that a variable identifying each observational unit/row should be included.</li>
</ol>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb19-1" data-line-number="1"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span>(tidyverse)</a>
<a class="sourceLine" id="cb19-2" data-line-number="2"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span>(moderndive)</a>
<a class="sourceLine" id="cb19-3" data-line-number="3"></a>
<a class="sourceLine" id="cb19-4" data-line-number="4"><span class="co"># Load in training and test set</span></a>
<a class="sourceLine" id="cb19-5" data-line-number="5">train &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">"https://github.com/moderndive/moderndive/raw/master/vignettes/train.csv"</span>)</a>
<a class="sourceLine" id="cb19-6" data-line-number="6">test &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">"https://github.com/moderndive/moderndive/raw/master/vignettes/test.csv"</span>)</a>
<a class="sourceLine" id="cb19-7" data-line-number="7"></a>
<a class="sourceLine" id="cb19-8" data-line-number="8"><span class="co"># Fit model</span></a>
<a class="sourceLine" id="cb19-9" data-line-number="9">house_model &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span>(SalePrice <span class="op">~</span><span class="st"> </span>YrSold, <span class="dt">data =</span> train)</a>
<a class="sourceLine" id="cb19-10" data-line-number="10"></a>
<a class="sourceLine" id="cb19-11" data-line-number="11"><span class="co"># Make and submit predictions</span></a>
<a class="sourceLine" id="cb19-12" data-line-number="12">submission &lt;-<span class="st"> </span><span class="kw"><a href="../reference/get_regression_points.html">get_regression_points</a></span>(house_model, <span class="dt">newdata =</span> test, <span class="dt">ID =</span> <span class="st">"Id"</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb19-13" data-line-number="13"><span class="st">  </span><span class="kw">select</span>(Id, <span class="dt">SalePrice =</span> SalePrice_hat)</a>
<a class="sourceLine" id="cb19-14" data-line-number="14"><span class="kw">write_csv</span>(submission, <span class="st">"submission.csv"</span>)</a></code></pre></div>
<p>Submitting <code>submission.csv</code> to the leaderboard for this Kaggle competition we get a “root mean squared logarithmic error” score of 0.42918, where smaller scores are better:</p>
<p><img src="leaderboard_orig.png" width="100%"></p>
<hr>
</div>
<div id="scalar-summaries-of-linear-regression-model-fits" class="section level2">
<h2 class="hasAnchor">
<a href="#scalar-summaries-of-linear-regression-model-fits" class="anchor"></a>5. Scalar summaries of linear regression model fits</h2>
<p>The fifth common student comment/question:</p>
<blockquote>
<p>“What is all this other stuff at the bottom?”</p>
</blockquote>
<p>Going back to the <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> from above, we figured it would be nice to be able to extract all the scalar summaries linear regression model fits. We’ve supplemented the standard scalar summaries output yielded by <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> with the mean squared error <code>mse</code> and root mean squared error <code>rmse</code> given their popularity in machine learning settings:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb20-1" data-line-number="1"><span class="kw"><a href="../reference/get_regression_summaries.html">get_regression_summaries</a></span>(score_model)</a>
<a class="sourceLine" id="cb20-2" data-line-number="2"><span class="co">#&gt; # A tibble: 1 x 8</span></a>
<a class="sourceLine" id="cb20-3" data-line-number="3"><span class="co">#&gt;   r_squared adj_r_squared   mse  rmse sigma statistic p_value    df</span></a>
<a class="sourceLine" id="cb20-4" data-line-number="4"><span class="co">#&gt;       &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;</span></a>
<a class="sourceLine" id="cb20-5" data-line-number="5"><span class="co">#&gt; 1     0.011         0.009 0.292 0.540 0.541      5.34   0.021     2</span></a></code></pre></div>
<hr>
</div>
<div id="the-details" class="section level2">
<h2 class="hasAnchor">
<a href="#the-details" class="anchor"></a>The Details</h2>
<p>The three <code>get_regression</code> functions are wrappers of functions from the <a href="https://CRAN.R-project.org/package=broom/vignettes/broom.html" target="_blank"><code>broom</code></a> package for converting statistical analysis objects into tidy tibbles along with a few added tweaks:</p>
<ol style="list-style-type: decimal">
<li>
<code><a href="../reference/get_regression_table.html">get_regression_table()</a></code> is a wrapper for <code><a href="https://rdrr.io/pkg/broom/man/reexports.html">broom::tidy()</a></code>
</li>
<li>
<code><a href="../reference/get_regression_points.html">get_regression_points()</a></code> is a wrapper for <code><a href="https://rdrr.io/pkg/broom/man/reexports.html">broom::augment()</a></code>
</li>
<li>
<code>get_regression_summaries</code> is a wrapper for <code><a href="https://rdrr.io/pkg/broom/man/reexports.html">broom::glance()</a></code>
</li>
</ol>
<p>Why did we take this approach to address the 5 common student questions/comments at the outset of the article?</p>
<ul>
<li>By writing wrappers to pre-existing functions, instead of creating new custom functions, there is minimal “re-inventing the wheel” necessary.</li>
<li>The <code>broom</code> package function names <code>tidy()</code>, <code>augment()</code>, and <code>glance()</code> don’t mean anything to intro stats students, where as the <code>moderndive</code> package function names <code><a href="../reference/get_regression_table.html">get_regression_table()</a></code>, <code><a href="../reference/get_regression_points.html">get_regression_points()</a></code>, and <code><a href="../reference/get_regression_summaries.html">get_regression_summaries()</a></code> are more intuitive.</li>
<li>The default column/variable names in the outputs of the above 3 functions are a little daunting for intro stats students to interpret. We cut out some of them and renamed many of them with more intuitive names. For example, compare the outputs of the <code><a href="../reference/get_regression_points.html">get_regression_points()</a></code> wrapper function and the parent <code><a href="https://rdrr.io/pkg/broom/man/reexports.html">broom::augment()</a></code> function.</li>
</ul>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb21-1" data-line-number="1"><span class="kw"><a href="../reference/get_regression_points.html">get_regression_points</a></span>(score_model)</a>
<a class="sourceLine" id="cb21-2" data-line-number="2"><span class="co">#&gt; # A tibble: 463 x 5</span></a>
<a class="sourceLine" id="cb21-3" data-line-number="3"><span class="co">#&gt;       ID score   age score_hat residual</span></a>
<a class="sourceLine" id="cb21-4" data-line-number="4"><span class="co">#&gt;    &lt;int&gt; &lt;dbl&gt; &lt;int&gt;     &lt;dbl&gt;    &lt;dbl&gt;</span></a>
<a class="sourceLine" id="cb21-5" data-line-number="5"><span class="co">#&gt;  1     1   4.7    36      4.25    0.452</span></a>
<a class="sourceLine" id="cb21-6" data-line-number="6"><span class="co">#&gt;  2     2   4.1    36      4.25   -0.148</span></a>
<a class="sourceLine" id="cb21-7" data-line-number="7"><span class="co">#&gt;  3     3   3.9    36      4.25   -0.348</span></a>
<a class="sourceLine" id="cb21-8" data-line-number="8"><span class="co">#&gt;  4     4   4.8    36      4.25    0.552</span></a>
<a class="sourceLine" id="cb21-9" data-line-number="9"><span class="co">#&gt;  5     5   4.6    59      4.11    0.488</span></a>
<a class="sourceLine" id="cb21-10" data-line-number="10"><span class="co">#&gt;  6     6   4.3    59      4.11    0.188</span></a>
<a class="sourceLine" id="cb21-11" data-line-number="11"><span class="co">#&gt;  7     7   2.8    59      4.11   -1.31 </span></a>
<a class="sourceLine" id="cb21-12" data-line-number="12"><span class="co">#&gt;  8     8   4.1    51      4.16   -0.059</span></a>
<a class="sourceLine" id="cb21-13" data-line-number="13"><span class="co">#&gt;  9     9   3.4    51      4.16   -0.759</span></a>
<a class="sourceLine" id="cb21-14" data-line-number="14"><span class="co">#&gt; 10    10   4.5    40      4.22    0.276</span></a>
<a class="sourceLine" id="cb21-15" data-line-number="15"><span class="co">#&gt; # … with 453 more rows</span></a>
<a class="sourceLine" id="cb21-16" data-line-number="16">broom<span class="op">::</span><span class="kw"><a href="https://rdrr.io/pkg/broom/man/reexports.html">augment</a></span>(score_model)</a>
<a class="sourceLine" id="cb21-17" data-line-number="17"><span class="co">#&gt; # A tibble: 463 x 9</span></a>
<a class="sourceLine" id="cb21-18" data-line-number="18"><span class="co">#&gt;    score   age .fitted .se.fit  .resid    .hat .sigma   .cooksd .std.resid</span></a>
<a class="sourceLine" id="cb21-19" data-line-number="19"><span class="co">#&gt;    &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;</span></a>
<a class="sourceLine" id="cb21-20" data-line-number="20"><span class="co">#&gt;  1   4.7    36    4.25  0.0405  0.452  0.00560  0.542 0.00197        0.837</span></a>
<a class="sourceLine" id="cb21-21" data-line-number="21"><span class="co">#&gt;  2   4.1    36    4.25  0.0405 -0.148  0.00560  0.542 0.000212      -0.274</span></a>
<a class="sourceLine" id="cb21-22" data-line-number="22"><span class="co">#&gt;  3   3.9    36    4.25  0.0405 -0.348  0.00560  0.542 0.00117       -0.645</span></a>
<a class="sourceLine" id="cb21-23" data-line-number="23"><span class="co">#&gt;  4   4.8    36    4.25  0.0405  0.552  0.00560  0.541 0.00294        1.02 </span></a>
<a class="sourceLine" id="cb21-24" data-line-number="24"><span class="co">#&gt;  5   4.6    59    4.11  0.0371  0.488  0.00471  0.541 0.00193        0.904</span></a>
<a class="sourceLine" id="cb21-25" data-line-number="25"><span class="co">#&gt;  6   4.3    59    4.11  0.0371  0.188  0.00471  0.542 0.000288       0.349</span></a>
<a class="sourceLine" id="cb21-26" data-line-number="26"><span class="co">#&gt;  7   2.8    59    4.11  0.0371 -1.31   0.00471  0.538 0.0139        -2.43 </span></a>
<a class="sourceLine" id="cb21-27" data-line-number="27"><span class="co">#&gt;  8   4.1    51    4.16  0.0261 -0.0591 0.00232  0.542 0.0000139     -0.109</span></a>
<a class="sourceLine" id="cb21-28" data-line-number="28"><span class="co">#&gt;  9   3.4    51    4.16  0.0261 -0.759  0.00232  0.541 0.00229       -1.40 </span></a>
<a class="sourceLine" id="cb21-29" data-line-number="29"><span class="co">#&gt; 10   4.5    40    4.22  0.0331  0.276  0.00374  0.542 0.000488       0.510</span></a>
<a class="sourceLine" id="cb21-30" data-line-number="30"><span class="co">#&gt; # … with 453 more rows</span></a></code></pre></div>
<p>If you’re curious to see how we designed these 3 functions, take a look at the source code on <a href="https://github.com/moderndive/moderndive/blob/master/R/regression_functions.R" target="_blank">GitHub</a>!</p>
<p>Many thanks to Max Kuhn <a href="https://github.com/topepo" target="_blank">@topepo</a> and Jenny Smetzer <a href="https://github.com/smetzer180" target="_blank">@smetzer180</a> for their helpful feedback for this vignette.</p>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#intro">Intro</a></li>
      <li><a href="#less-p-value-stars-more-confidence-intervals">1. Less p-value stars, more confidence intervals</a></li>
      <li><a href="#outputs-as-tidy-tibbles">2. Outputs as tidy tibbles!</a></li>
      <li><a href="#birds-of-a-feather-should-flock-together-fitted-values-residuals">3. Birds of a feather should flock together: Fitted values &amp; residuals</a></li>
      <li><a href="#babys-first-kaggle-predictive-modeling-competition-submission">4. Baby’s first Kaggle predictive modeling competition submission!</a></li>
      <li><a href="#scalar-summaries-of-linear-regression-model-fits">5. Scalar summaries of linear regression model fits</a></li>
      <li><a href="#the-details">The Details</a></li>
      </ul>
</div>
      </div>

</div>



      <footer><div class="copyright">
  <p>Developed by Albert Y. Kim, Chester Ismay.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.3.0.9100.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
